[package]
name = "trying-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "*"
web-sys = { version = "*", features = ["MouseEvent", "Window", "HtmlDocument", "HtmlElement", "HtmlInputElement"] }
